# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               codeworm96 
tagline:             'blog'
description:         'Records of coding'
url:                 http://codeworm96.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              codeworm96
  url:               http://codeworm96.github.io/
  email:             codeworm96@outlook.com

# Custom vars
version:             1.0.0
